routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/verification', 'ChatController@verification');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Chat
Route::post('/messages/checkchat', 'ChatController@checkchat')->name('checkchat');
Route::get('/messages/chat-{room}', 'ChatController@show')->name('chat');
Route::get('/messages/{room}', 'ChatController@fetchMessages');
Route::post('/messages', 'ChatController@sendMessage');
Route::post('/messages/checkroom', 'ChatController@checkRoom')->name('check-room');
Route::post('/messages/dropzone', 'ChatController@dropzone')->name('dropzone');
Route::post('/messages/getFiles', 'ChatController@getFiles')->name('getFiles');
Route::post('/messages/deleteFile', 'ChatController@deleteFile')->name('deleteFile');

Route::get('/srvtime', 'ChatController@srvtime');
//Route::get('/room/join/{roomName}', 'VideoRoomsController@joinRoom');
//Route::post('/room/create', 'VideoRoomsController@createRoom');

Route::get('/admin-lte', 'Admin\AdminController@index')->name('admin-lte');
Route::get('/mails', 'Admin\AdminController@getMails')->name('mails');
Route::get('/reservations', 'Admin\AdminController@getReservations')->name('reservations');
Route::resource('/bookings', 'Admin\BookingController');
Route::resource('/users', 'Admin\UserController');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * @param $email
     */
    public function setEmailAttribute($email)
    {
        $this->attributes['email'] = strtolower($email);
    }

    /**
     * @param $password
     */
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }

    /**
     * A user belongs to many rooms
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function rooms()
    {
        return $this->belongsToMany('App\Models\Room');
    }

    /**
     * A user can have many messages
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function messages()
    {
        return $this->hasMany('App\Models\Message');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: Aks13
 * Date: 10.01.2019
 * Time: 11:39
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Auth;

class UserController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = User::whereNotIn('id',User::role('Admin')->pluck('id'))->orderBy('name')->paginate(10);
        return view('admin.user.index',['users'=>$users]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {

        $user->delete();
        return redirect()->route('users.index');
    }
}

resources/views/admin/user/index.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('common.users'))
@section('content-title', __('common.users'))

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('admin-lte') }}"><i class="fa fa-dashboard"></i> {{ __('common.dashboard') }}</a></li>
        <li class="active"><i class="fa fa-user-secret"></i> {{ __('common.users') }}</li>
    </ol>
@endsection

@section('content')
    <div class="box">
        <div class="box-body">
            <table class="table table-condensed table-responsive table-hover">
                <thead>
                <tr>
                    <th>{{ __('common.user') }}</th>
                    <th>{{ __('common.email') }}</th>
                </tr>
                </thead>
                <tbody>
                @forelse($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>
                            {{--<a href="{{ route('bookings.edit', $booking) }}" class="btn btn-info pull-left btn-sm button_right_shift">--}}
                                {{--<i class="fa fa-edit"></i>--}}
                            {{--</a>--}}

                            <form onsubmit="if(confirm('{{ __('common.deleting') }}')){ return true }else{ return false }" action="{{ route('users.destroy', $user) }}" method="post">
                                <input type="hidden" name="_method" value="delete" />
                                {{csrf_field()}}
                                <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td><h2>{{ __('common.empty') }}</h2></td>
                    </tr>
                @endforelse
                </tbody>
                <tfoot>
                <tr>
                    <td>
                        <nav aria-label="page navigation">
                            <ul class="pagination">
                                {{$users->links()}}
                            </ul>
                        </nav>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection